dune-istl: Dune::CompressedBlockVectorWindow< B, A > Class Template Reference
Dune::CompressedBlockVectorWindow< B, A > Class Template Reference
#include <dune/istl/bvector.hh>
Public Types
enum { blocklevel = B::blocklevel+1 }
increment block level counter
typedef B::field_type field_type
export the type representing the field
typedef B block_type
export the type representing the components
typedef A allocator_type
export the allocator type
typedef A::size_type size_type
The type for the index access.
typedef
compressed_block_vector_unmanaged
< B, A >::Iterator Iterator
make iterators available as types
typedef
compressed_block_vector_unmanaged
< B, A >::ConstIterator ConstIterator
make iterators available as types
typedef B member_type
export the type representing the components
typedef RealIterator< B > iterator
The iterator type.
typedef RealIterator< const B > const_iterator
const_iterator class for sequential access
Public Member Functions
CompressedBlockVectorWindow ()
makes empty array
CompressedBlockVectorWindow (B *_p, size_type *_j, size_type _n)
make array from given pointers and size
CompressedBlockVectorWindow (const CompressedBlockVectorWindow &a)
copy constructor, this has reference semantics!
CompressedBlockVectorWindow (const compressed_block_vector_unmanaged< B, A > &_a)
construct from base class object with reference semantics!
CompressedBlockVectorWindow & operator= (const CompressedBlockVectorWindow &a)
assignment
CompressedBlockVectorWindow & operator= (const compressed_block_vector_unmanaged< B, A > &a)
assign from base class object
CompressedBlockVectorWindow & operator= (const field_type &k)
assign from scalar
void set (size_type _n, B *_p, size_type *_j)
set size and pointer
void setsize (size_type _n)
set size only
void setptr (B *_p)
set pointer only
void setindexptr (size_type *_j)
set pointer only
B * getptr ()
get pointer
size_type * getindexptr ()
get pointer
const B * getptr () const
get pointer
const size_type * getindexptr () const
get pointer
size_type getsize () const
get size
template<class V >
compressed_block_vector_unmanaged & operator+= (const V &y)
vector space addition
template<class V >
compressed_block_vector_unmanaged & operator-= (const V &y)
vector space subtraction
template<class V >
compressed_block_vector_unmanaged & axpy (const field_type &a, const V &y)
vector space axpy operation
compressed_block_vector_unmanaged & operator*= (const field_type &k)
vector space multiplication with scalar
compressed_block_vector_unmanaged & operator/= (const field_type &k)
vector space division by scalar
field_type operator* (const compressed_block_vector_unmanaged &y) const
scalar product
double one_norm () const
one norm (sum over absolute values of entries)
double one_norm_real () const
simplified one norm (uses Manhattan norm for complex values)
double two_norm () const
two norm sqrt(sum over squared values of entries)
double two_norm2 () const
sqare of two norm (sum over squared values of entries), need for block recursion
double infinity_norm () const
infinity norm (maximum of absolute values of entries)
double infinity_norm_real () const
simplified infinity norm (uses Manhattan norm for complex values)
size_type N () const
number of blocks in the vector (are of size 1 here)
size_type dim () const
dimension of the vector space
B & operator[] (size_type i)
random access to blocks, assumes ascending ordering
const B & operator[] (size_type i) const
same for read only access, assumes ascending ordering
iterator begin ()
begin iterator
const_iterator begin () const
begin const_iterator
iterator end ()
end iterator
const_iterator end () const
end const_iterator
iterator beforeEnd ()
const_iterator beforeEnd () const
iterator beforeBegin ()
const_iterator beforeBegin () const
iterator find (size_type i)
random access returning iterator (end if not contained)
const_iterator find (size_type i) const
random access returning iterator (end if not contained)
size_type size () const
number of blocks in the array (are of size 1 here)
Protected Member Functions
template<class V >
bool includesindexset (const V &y)
return true if index sets coincide
Protected Attributes
size_type n
B * p
size_type * j
Detailed Description
template<class B, class A = std::allocator<B>>
class Dune::CompressedBlockVectorWindow< B, A >
CompressedBlockVectorWindow adds window manipulation functions to the compressed_block_vector_unmanaged template.
This class has no memory management. It assumes that the storage for the entries of the vector and its index set is maintained outside of this class.
But you can copy objects of this class and of the base class with reference semantics.
Assignment copies the data, if the format is incopmpatible with
the argument an exception is thrown in debug mode.
Error checking: no error checking is provided normally.
Setting the compile time switch DUNE_ISTL_WITH_CHECKING
enables error checking.
Member Typedef Documentation
template<class B , class A = std::allocator<B>> typedef A Dune::CompressedBlockVectorWindow< B, A >::allocator_type
export the allocator type
Reimplemented from Dune::compressed_block_vector_unmanaged< B, A >.
template<class B , class A = std::allocator<B>> typedef B Dune::CompressedBlockVectorWindow< B, A >::block_type
export the type representing the components
Reimplemented from Dune::compressed_block_vector_unmanaged< B, A >.
template<class B , class A = std::allocator<B>> typedef RealIterator<const B> Dune::compressed_base_array_unmanaged< B, A >::const_iterator inherited
const_iterator class for sequential access
template<class B , class A = std::allocator<B>> typedef compressed_block_vector_unmanaged<B,A>::ConstIterator Dune::CompressedBlockVectorWindow< B, A >::ConstIterator
make iterators available as types
Reimplemented from Dune::compressed_block_vector_unmanaged< B, A >.
template<class B , class A = std::allocator<B>> typedef B::field_type Dune::CompressedBlockVectorWindow< B, A >::field_type
export the type representing the field
Reimplemented from Dune::compressed_block_vector_unmanaged< B, A >.
template<class B , class A = std::allocator<B>> typedef RealIterator<B> Dune::compressed_base_array_unmanaged< B, A >::iterator inherited
The iterator type.
template<class B , class A = std::allocator<B>> typedef compressed_block_vector_unmanaged<B,A>::Iterator Dune::CompressedBlockVectorWindow< B, A >::Iterator
make iterators available as types
Reimplemented from Dune::compressed_block_vector_unmanaged< B, A >.
template<class B , class A = std::allocator<B>> typedef B Dune::compressed_base_array_unmanaged< B, A >::member_type inherited
export the type representing the components
template<class B , class A = std::allocator<B>> typedef A::size_type Dune::CompressedBlockVectorWindow< B, A >::size_type
The type for the index access.
Reimplemented from Dune::compressed_block_vector_unmanaged< B, A >.
Member Enumeration Documentation
template<class B , class A = std::allocator<B>> anonymous enum
increment block level counter
Enumerator:
blocklevel
The number of block level this vector contains.
Constructor & Destructor Documentation
template<class B , class A = std::allocator<B>> Dune::CompressedBlockVectorWindow< B, A >::CompressedBlockVectorWindow () inline
makes empty array
template<class B , class A = std::allocator<B>> Dune::CompressedBlockVectorWindow< B, A >::CompressedBlockVectorWindow (B * _p, size_type * _j, size_type _n) inline
make array from given pointers and size
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> Dune::CompressedBlockVectorWindow< B, A >::CompressedBlockVectorWindow (const CompressedBlockVectorWindow< B, A > & a) inline
copy constructor, this has reference semantics!
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> Dune::CompressedBlockVectorWindow< B, A >::CompressedBlockVectorWindow (const compressed_block_vector_unmanaged< B, A > & _a) inline
construct from base class object with reference semantics!
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
Member Function Documentation
template<class B, class A = std::allocator<B>> template<class V > compressed_block_vector_unmanaged& Dune::compressed_block_vector_unmanaged< B, A >::axpy (const field_type & a, const V & y) inline inherited
vector space axpy operation
References Dune::compressed_block_vector_unmanaged< B, A >::includesindexset().
template<class B , class A = std::allocator<B>> iterator Dune::compressed_base_array_unmanaged< B, A >::beforeBegin () inline inherited
Returns:
an iterator that is positioned before the first entry of the vector.
References Dune::compressed_base_array_unmanaged< B, A >::j, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> const_iterator Dune::compressed_base_array_unmanaged< B, A >::beforeBegin () const inline inherited
Returns:
an iterator that is positioned before the first entry of the vector.
References Dune::compressed_base_array_unmanaged< B, A >::j, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> iterator Dune::compressed_base_array_unmanaged< B, A >::beforeEnd () inline inherited
Returns:
an iterator that is positioned before the end iterator of the vector, i.e. at the last entry.
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> const_iterator Dune::compressed_base_array_unmanaged< B, A >::beforeEnd () const inline inherited
Returns:
an iterator that is positioned before the end iterator of the vector. i.e. at the last element.
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> iterator Dune::compressed_base_array_unmanaged< B, A >::begin () inline inherited
begin iterator
References Dune::compressed_base_array_unmanaged< B, A >::j, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> const_iterator Dune::compressed_base_array_unmanaged< B, A >::begin () const inline inherited
begin const_iterator
References Dune::compressed_base_array_unmanaged< B, A >::j, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B, class A = std::allocator<B>> size_type Dune::compressed_block_vector_unmanaged< B, A >::dim () const inline inherited
dimension of the vector space
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> iterator Dune::compressed_base_array_unmanaged< B, A >::end () inline inherited
end iterator
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
Referenced by Dune::compressed_block_vector_unmanaged< B, A >::includesindexset().
template<class B , class A = std::allocator<B>> const_iterator Dune::compressed_base_array_unmanaged< B, A >::end () const inline inherited
end const_iterator
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> iterator Dune::compressed_base_array_unmanaged< B, A >::find (size_type i) inline inherited
random access returning iterator (end if not contained)
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
Referenced by Dune::compressed_block_vector_unmanaged< B, A >::includesindexset().
template<class B , class A = std::allocator<B>> const_iterator Dune::compressed_base_array_unmanaged< B, A >::find (size_type i) const inline inherited
random access returning iterator (end if not contained)
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> size_type* Dune::CompressedBlockVectorWindow< B, A >::getindexptr () inline
get pointer
References Dune::compressed_base_array_unmanaged< B, A >::j.
Referenced by Dune::BCRSMatrix< B, A >::addindex(), Dune::MatrixDimension< BCRSMatrix< B, TA > >::coldim(), and Dune::BCRSMatrix< B, A >::CreateIterator::operator++().
template<class B , class A = std::allocator<B>> const size_type* Dune::CompressedBlockVectorWindow< B, A >::getindexptr () const inline
get pointer
References Dune::compressed_base_array_unmanaged< B, A >::j.
template<class B , class A = std::allocator<B>> B* Dune::CompressedBlockVectorWindow< B, A >::getptr () inline
get pointer
References Dune::compressed_base_array_unmanaged< B, A >::p.
Referenced by Dune::MatrixDimension< BCRSMatrix< B, TA > >::coldim(), Dune::BCRSMatrix< B, A >::CreateIterator::operator++(), and Dune::MatrixDimension< BCRSMatrix< B, TA > >::rowdim().
template<class B , class A = std::allocator<B>> const B* Dune::CompressedBlockVectorWindow< B, A >::getptr () const inline
get pointer
References Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> size_type Dune::CompressedBlockVectorWindow< B, A >::getsize () const inline
get size
References Dune::compressed_base_array_unmanaged< B, A >::n.
Referenced by Dune::BCRSMatrix< B, A >::addindex(), Dune::BCRSMatrix< B, A >::BCRSMatrix(), Dune::MatrixDimension< BCRSMatrix< B, TA > >::coldim(), Dune::BCRSMatrix< B, A >::endrowsizes(), Dune::BCRSMatrix< B, A >::getrowsize(), and Dune::BCRSMatrix< B, A >::operator=().
template<class B, class A = std::allocator<B>> template<class V > bool Dune::compressed_block_vector_unmanaged< B, A >::includesindexset (const V & y) inline protected inherited
return true if index sets coincide
References Dune::compressed_base_array_unmanaged< B, A >::end(), and Dune::compressed_base_array_unmanaged< B, A >::find().
Referenced by Dune::compressed_block_vector_unmanaged< B, A >::axpy(), Dune::compressed_block_vector_unmanaged< B, A >::operator*(), Dune::compressed_block_vector_unmanaged< B, A >::operator+=(), and Dune::compressed_block_vector_unmanaged< B, A >::operator-=().
template<class B, class A = std::allocator<B>> double Dune::compressed_block_vector_unmanaged< B, A >::infinity_norm () const inline inherited
infinity norm (maximum of absolute values of entries)
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B, class A = std::allocator<B>> double Dune::compressed_block_vector_unmanaged< B, A >::infinity_norm_real () const inline inherited
simplified infinity norm (uses Manhattan norm for complex values)
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B, class A = std::allocator<B>> size_type Dune::compressed_block_vector_unmanaged< B, A >::N () const inline inherited
number of blocks in the vector (are of size 1 here)
References Dune::compressed_base_array_unmanaged< B, A >::n.
Referenced by Dune::CompressedBlockVectorWindow< B, A >::operator=().
template<class B, class A = std::allocator<B>> double Dune::compressed_block_vector_unmanaged< B, A >::one_norm () const inline inherited
one norm (sum over absolute values of entries)
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B, class A = std::allocator<B>> double Dune::compressed_block_vector_unmanaged< B, A >::one_norm_real () const inline inherited
simplified one norm (uses Manhattan norm for complex values)
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B, class A = std::allocator<B>> field_type Dune::compressed_block_vector_unmanaged< B, A >::operator* (const compressed_block_vector_unmanaged< B, A > & y) const inline inherited
scalar product
References Dune::compressed_block_vector_unmanaged< B, A >::includesindexset(), Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B, class A = std::allocator<B>> compressed_block_vector_unmanaged& Dune::compressed_block_vector_unmanaged< B, A >::operator*= (const field_type & k) inline inherited
vector space multiplication with scalar
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B, class A = std::allocator<B>> template<class V > compressed_block_vector_unmanaged& Dune::compressed_block_vector_unmanaged< B, A >::operator+= (const V & y) inline inherited
vector space addition
References Dune::compressed_block_vector_unmanaged< B, A >::includesindexset().
template<class B, class A = std::allocator<B>> template<class V > compressed_block_vector_unmanaged& Dune::compressed_block_vector_unmanaged< B, A >::operator-= (const V & y) inline inherited
vector space subtraction
References Dune::compressed_block_vector_unmanaged< B, A >::includesindexset().
template<class B, class A = std::allocator<B>> compressed_block_vector_unmanaged& Dune::compressed_block_vector_unmanaged< B, A >::operator/= (const field_type & k) inline inherited
vector space division by scalar
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> CompressedBlockVectorWindow& Dune::CompressedBlockVectorWindow< B, A >::operator= (const CompressedBlockVectorWindow< B, A > & a) inline
assignment
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, Dune::compressed_block_vector_unmanaged< B, A >::N(), and Dune::compressed_base_array_unmanaged< B, A >::p.
Referenced by Dune::CompressedBlockVectorWindow< B, A >::operator=().
template<class B , class A = std::allocator<B>> CompressedBlockVectorWindow& Dune::CompressedBlockVectorWindow< B, A >::operator= (const compressed_block_vector_unmanaged< B, A > & a) inline
assign from base class object
References Dune::CompressedBlockVectorWindow< B, A >::operator=().
template<class B , class A = std::allocator<B>> CompressedBlockVectorWindow& Dune::CompressedBlockVectorWindow< B, A >::operator= (const field_type & k) inline
assign from scalar
Reimplemented from Dune::compressed_block_vector_unmanaged< B, A >.
template<class B , class A = std::allocator<B>> B& Dune::compressed_base_array_unmanaged< B, A >::operator[] (size_type i) inline inherited
random access to blocks, assumes ascending ordering
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> const B& Dune::compressed_base_array_unmanaged< B, A >::operator[] (size_type i) const inline inherited
same for read only access, assumes ascending ordering
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B , class A = std::allocator<B>> void Dune::CompressedBlockVectorWindow< B, A >::set (size_type _n, B * _p, size_type * _j) inline
set size and pointer
References Dune::compressed_base_array_unmanaged< B, A >::j, Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
Referenced by Dune::BCRSMatrix< B, A >::CreateIterator::operator++().
template<class B , class A = std::allocator<B>> void Dune::CompressedBlockVectorWindow< B, A >::setindexptr (size_type * _j) inline
set pointer only
References Dune::compressed_base_array_unmanaged< B, A >::j.
Referenced by Dune::BCRSMatrix< B, A >::CreateIterator::operator++().
template<class B , class A = std::allocator<B>> void Dune::CompressedBlockVectorWindow< B, A >::setptr (B * _p) inline
set pointer only
References Dune::compressed_base_array_unmanaged< B, A >::p.
Referenced by Dune::BCRSMatrix< B, A >::CreateIterator::operator++().
template<class B , class A = std::allocator<B>> void Dune::CompressedBlockVectorWindow< B, A >::setsize (size_type _n) inline
set size only
References Dune::compressed_base_array_unmanaged< B, A >::n.
Referenced by Dune::BCRSMatrix< B, A >::endindices(), Dune::BCRSMatrix< B, A >::incrementrowsize(), and Dune::BCRSMatrix< B, A >::setrowsize().
template<class B , class A = std::allocator<B>> size_type Dune::compressed_base_array_unmanaged< B, A >::size () const inline inherited
number of blocks in the array (are of size 1 here)
References Dune::compressed_base_array_unmanaged< B, A >::n.
template<class B, class A = std::allocator<B>> double Dune::compressed_block_vector_unmanaged< B, A >::two_norm () const inline inherited
two norm sqrt(sum over squared values of entries)
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
template<class B, class A = std::allocator<B>> double Dune::compressed_block_vector_unmanaged< B, A >::two_norm2 () const inline inherited
sqare of two norm (sum over squared values of entries), need for block recursion
References Dune::compressed_base_array_unmanaged< B, A >::n, and Dune::compressed_base_array_unmanaged< B, A >::p.
Member Data Documentation
template<class B , class A = std::allocator<B>> size_type* Dune::compressed_base_array_unmanaged< B, A >::j protected inherited
Referenced by Dune::compressed_base_array_unmanaged< B, A >::beforeBegin(), Dune::compressed_base_array_unmanaged< B, A >::beforeEnd(), Dune::compressed_base_array_unmanaged< B, A >::begin(), Dune::CompressedBlockVectorWindow< B, A >::CompressedBlockVectorWindow(), Dune::compressed_base_array_unmanaged< B, A >::end(), Dune::compressed_base_array_unmanaged< B, A >::find(), Dune::CompressedBlockVectorWindow< B, A >::getindexptr(), Dune::compressed_block_vector_unmanaged< B, A >::operator*(), Dune::CompressedBlockVectorWindow< B, A >::operator=(), Dune::compressed_base_array_unmanaged< B, A >::operator[](), Dune::CompressedBlockVectorWindow< B, A >::set(), and Dune::CompressedBlockVectorWindow< B, A >::setindexptr().
template<class B , class A = std::allocator<B>> size_type Dune::compressed_base_array_unmanaged< B, A >::n protected inherited
Referenced by Dune::compressed_base_array_unmanaged< B, A >::beforeEnd(), Dune::CompressedBlockVectorWindow< B, A >::CompressedBlockVectorWindow(), Dune::compressed_block_vector_unmanaged< B, A >::dim(), Dune::compressed_base_array_unmanaged< B, A >::end(), Dune::compressed_base_array_unmanaged< B, A >::find(), Dune::CompressedBlockVectorWindow< B, A >::getsize(), Dune::compressed_block_vector_unmanaged< B, A >::infinity_norm(), Dune::compressed_block_vector_unmanaged< B, A >::infinity_norm_real(), Dune::compressed_block_vector_unmanaged< B, A >::N(), Dune::compressed_block_vector_unmanaged< B, A >::one_norm(), Dune::compressed_block_vector_unmanaged< B, A >::one_norm_real(), Dune::compressed_block_vector_unmanaged< B, A >::operator*(), Dune::compressed_block_vector_unmanaged< B, A >::operator*=(), Dune::compressed_block_vector_unmanaged< B, A >::operator/=(), Dune::compressed_block_vector_unmanaged< B, A >::operator=(), Dune::CompressedBlockVectorWindow< B, A >::operator=(), Dune::compressed_base_array_unmanaged< B, A >::operator[](), Dune::CompressedBlockVectorWindow< B, A >::set(), Dune::CompressedBlockVectorWindow< B, A >::setsize(), Dune::compressed_base_array_unmanaged< B, A >::size(), Dune::compressed_block_vector_unmanaged< B, A >::two_norm(), and Dune::compressed_block_vector_unmanaged< B, A >::two_norm2().
template<class B , class A = std::allocator<B>> B* Dune::compressed_base_array_unmanaged< B, A >::p protected inherited
Referenced by Dune::compressed_base_array_unmanaged< B, A >::beforeBegin(), Dune::compressed_base_array_unmanaged< B, A >::beforeEnd(), Dune::compressed_base_array_unmanaged< B, A >::begin(), Dune::CompressedBlockVectorWindow< B, A >::CompressedBlockVectorWindow(), Dune::compressed_block_vector_unmanaged< B, A >::dim(), Dune::compressed_base_array_unmanaged< B, A >::end(), Dune::compressed_base_array_unmanaged< B, A >::find(), Dune::CompressedBlockVectorWindow< B, A >::getptr(), Dune::compressed_block_vector_unmanaged< B, A >::infinity_norm(), Dune::compressed_block_vector_unmanaged< B, A >::infinity_norm_real(), Dune::compressed_block_vector_unmanaged< B, A >::one_norm(), Dune::compressed_block_vector_unmanaged< B, A >::one_norm_real(), Dune::compressed_block_vector_unmanaged< B, A >::operator*(), Dune::compressed_block_vector_unmanaged< B, A >::operator*=(), Dune::compressed_block_vector_unmanaged< B, A >::operator/=(), Dune::compressed_block_vector_unmanaged< B, A >::operator=(), Dune::CompressedBlockVectorWindow< B, A >::operator=(), Dune::compressed_base_array_unmanaged< B, A >::operator[](), Dune::CompressedBlockVectorWindow< B, A >::set(), Dune::CompressedBlockVectorWindow< B, A >::setptr(), Dune::compressed_block_vector_unmanaged< B, A >::two_norm(), and Dune::compressed_block_vector_unmanaged< B, A >::two_norm2().
The documentation for this class was generated from the following file:
bvector.hh