dune-istl: Dune::VariableBlockVector< B, A >::CreateIterator Class Reference
Dune::VariableBlockVector< B, A >::CreateIterator Class Reference
Iterator class for sequential creation of blocks.
#include <dune/istl/vbvector.hh>
Public Member Functions
CreateIterator (VariableBlockVector &_v, int _i)
constructor
CreateIterator & operator++ ()
prefix increment
bool operator!= (const CreateIterator &it) const
inequality
bool operator== (const CreateIterator &it) const
equality
size_type index () const
dereferencing
void setblocksize (size_type _k)
set size of current block
Detailed Description
template<class B, class A = std::allocator<B>>
class Dune::VariableBlockVector< B, A >::CreateIterator
Iterator class for sequential creation of blocks.
Constructor & Destructor Documentation
template<class B, class A = std::allocator<B>> Dune::VariableBlockVector< B, A >::CreateIterator::CreateIterator (VariableBlockVector & _v, int _i) inline
constructor
Member Function Documentation
template<class B, class A = std::allocator<B>> size_type Dune::VariableBlockVector< B, A >::CreateIterator::index () const inline
dereferencing
template<class B, class A = std::allocator<B>> bool Dune::VariableBlockVector< B, A >::CreateIterator::operator!= (const CreateIterator & it) const inline
inequality
template<class B, class A = std::allocator<B>> CreateIterator& Dune::VariableBlockVector< B, A >::CreateIterator::operator++ () inline
prefix increment
References Dune::BlockVectorWindow< B, A >::getptr(), Dune::BlockVectorWindow< B, A >::getsize(), Dune::base_array_unmanaged< B, A >::n, Dune::base_array_unmanaged< B, A >::p, Dune::BlockVectorWindow< B, A >::setptr(), and Dune::BlockVectorWindow< B, A >::setsize().
template<class B, class A = std::allocator<B>> bool Dune::VariableBlockVector< B, A >::CreateIterator::operator== (const CreateIterator & it) const inline
equality
template<class B, class A = std::allocator<B>> void Dune::VariableBlockVector< B, A >::CreateIterator::setblocksize (size_type _k) inline
set size of current block
The documentation for this class was generated from the following file:
vbvector.hh