dune-istl: Dune::CheckIfDiagonalPresent< Matrix, blocklevel, l > Struct Template Reference
Dune::CheckIfDiagonalPresent< Matrix, blocklevel, l > Struct Template Reference
Sparse Matrix and Vector classes
Check whether the a matrix has diagonal values on blocklevel recursion levels.
#include <dune/istl/matrixutils.hh>
Static Public Member Functions
static void check (const Matrix &mat)
Check whether the a matrix has diagonal values on blocklevel recursion levels.
Detailed Description
template<class Matrix, std::size_t blocklevel, std::size_t l = blocklevel>
struct Dune::CheckIfDiagonalPresent< Matrix, blocklevel, l >
Check whether the a matrix has diagonal values on blocklevel recursion levels.
Member Function Documentation
template<class Matrix , std::size_t blocklevel, std::size_t l = blocklevel> static void Dune::CheckIfDiagonalPresent< Matrix, blocklevel, l >::check (const Matrix & mat) inline static
Check whether the a matrix has diagonal values on blocklevel recursion levels.
References Dune::Matrix< T, A >::begin(), Dune::Matrix< T, A >::end(), and row.
Referenced by Dune::SeqGS< M, X, Y, l >::SeqGS(), and Dune::SeqJac< M, X, Y, l >::SeqJac().
The documentation for this struct was generated from the following file:
matrixutils.hh