dune-istl: Dune::algmeta_itsteps< I > Struct Template Reference
Dune::algmeta_itsteps< I > Struct Template Reference
Block Recursive Iterative Kernels
#include <dune/istl/gsetc.hh>
Static Public Member Functions
template<class M , class X , class Y , class K >
static void dbgs (const M &A, X &x, const Y &b, const K &w)
template<class M , class X , class Y , class K >
static void bsorf (const M &A, X &x, const Y &b, const K &w)
template<class M , class X , class Y , class K >
static void bsorb (const M &A, X &x, const Y &b, const K &w)
template<class M , class X , class Y , class K >
static void dbjac (const M &A, X &x, const Y &b, const K &w)
Member Function Documentation
template<int I> template<class M , class X , class Y , class K > static void Dune::algmeta_itsteps< I >::bsorb (const M & A, X & x, const Y & b, const K & w) inline static
Referenced by Dune::bsorb().
template<int I> template<class M , class X , class Y , class K > static void Dune::algmeta_itsteps< I >::bsorf (const M & A, X & x, const Y & b, const K & w) inline static
Referenced by Dune::bsorf().
template<int I> template<class M , class X , class Y , class K > static void Dune::algmeta_itsteps< I >::dbgs (const M & A, X & x, const Y & b, const K & w) inline static
Referenced by Dune::dbgs().
template<int I> template<class M , class X , class Y , class K > static void Dune::algmeta_itsteps< I >::dbjac (const M & A, X & x, const Y & b, const K & w) inline static
Referenced by Dune::dbjac().
The documentation for this struct was generated from the following file:
gsetc.hh