dune-istl: Dune::MatrixRowSubset< M, S > Class Template Reference
Dune::MatrixRowSubset< M, S > Class Template Reference
Provides access to an iterator over an arbitrary subset of matrix rows.
#include <dune/istl/supermatrix.hh>
Classes
class const_iterator
Public Types
typedef M Matrix
typedef S RowIndexSet
Public Member Functions
MatrixRowSubset (const Matrix &m, const RowIndexSet &s)
Construct an row set over all matrix rows.
const Matrix & matrix () const
const RowIndexSet & rowIndexSet () const
const_iterator begin () const
const_iterator end () const
Detailed Description
template<class M, class S>
class Dune::MatrixRowSubset< M, S >
Provides access to an iterator over an arbitrary subset of matrix rows.
Template Parameters:
M The type of the matrix.
S the type of the set of valid row indices.
Member Typedef Documentation
template<class M, class S> typedef M Dune::MatrixRowSubset< M, S >::Matrix
template<class M, class S> typedef S Dune::MatrixRowSubset< M, S >::RowIndexSet
Constructor & Destructor Documentation
template<class M, class S> Dune::MatrixRowSubset< M, S >::MatrixRowSubset (const Matrix & m, const RowIndexSet & s) inline
Construct an row set over all matrix rows.
Parameters:
m The matrix for which we manage the rows.
s The set of row indices we manage.
Member Function Documentation
template<class M, class S> const_iterator Dune::MatrixRowSubset< M, S >::begin () const inline
Referenced by Dune::copyToSuperMatrix().
template<class M, class S> const_iterator Dune::MatrixRowSubset< M, S >::end () const inline
Referenced by Dune::copyToSuperMatrix().
template<class M, class S> const Matrix& Dune::MatrixRowSubset< M, S >::matrix () const inline
Referenced by Dune::copyToSuperMatrix().
template<class M, class S> const RowIndexSet& Dune::MatrixRowSubset< M, S >::rowIndexSet () const inline
Referenced by Dune::copyToSuperMatrix().
The documentation for this class was generated from the following file:
supermatrix.hh