dune-istl: Dune::MatrixDimension< BCRSMatrix< B, TA > > Struct Template Reference
Dune::MatrixDimension< BCRSMatrix< B, TA > > Struct Template Reference
#include <dune/istl/matrixutils.hh>
Public Types
typedef BCRSMatrix< B, TA > Matrix
typedef Matrix::block_type block_type
typedef Matrix::size_type size_type
Static Public Member Functions
static size_type rowdim (const Matrix &A, size_type i)
static size_type coldim (const Matrix &A, size_type c)
static size_type rowdim (const Matrix &A)
static size_type coldim (const Matrix &A)
Member Typedef Documentation
template<typename B , typename TA > typedef Matrix::block_type Dune::MatrixDimension< BCRSMatrix< B, TA > >::block_type
template<typename B , typename TA > typedef BCRSMatrix<B,TA> Dune::MatrixDimension< BCRSMatrix< B, TA > >::Matrix
template<typename B , typename TA > typedef Matrix::size_type Dune::MatrixDimension< BCRSMatrix< B, TA > >::size_type
Member Function Documentation
template<typename B , typename TA > static size_type Dune::MatrixDimension< BCRSMatrix< B, TA > >::coldim (const Matrix & A, size_type c) inline static
References Dune::CompressedBlockVectorWindow< B, A >::getindexptr(), Dune::CompressedBlockVectorWindow< B, A >::getptr(), Dune::CompressedBlockVectorWindow< B, A >::getsize(), and Dune::BCRSMatrix< B, A >::N().
template<typename B , typename TA > static size_type Dune::MatrixDimension< BCRSMatrix< B, TA > >::coldim (const Matrix & A) inline static
References Dune::BCRSMatrix< B, A >::begin(), col, Dune::BCRSMatrix< B, A >::end(), Dune::BCRSMatrix< B, A >::M(), and row.
template<typename B , typename TA > static size_type Dune::MatrixDimension< BCRSMatrix< B, TA > >::rowdim (const Matrix & A, size_type i) inline static
References Dune::CompressedBlockVectorWindow< B, A >::getptr(), and row.
template<typename B , typename TA > static size_type Dune::MatrixDimension< BCRSMatrix< B, TA > >::rowdim (const Matrix & A) inline static
References Dune::BCRSMatrix< B, A >::N().
The documentation for this struct was generated from the following file:
matrixutils.hh