dune-istl: Dune::MatrixIndexSet Class Reference
Dune::MatrixIndexSet Class Reference
Stores the nonzero entries in a sparse matrix.
#include <dune/istl/matrixindexset.hh>
Public Types
typedef std::size_t size_type
Public Member Functions
MatrixIndexSet ()
Default constructor.
MatrixIndexSet (size_type rows, size_type cols)
Constructor setting the matrix size.
void resize (size_type rows, size_type cols)
Reset the size of an index set.
void add (size_type i, size_type j)
Add an index to the index set.
size_type size () const
Return the number of entries.
size_type rows () const
Return the number of rows.
size_type rowsize (size_type row) const
Return the number of entries in a given row.
template<class MatrixType >
void import (const MatrixType &m, size_type rowOffset=0, size_type colOffset=0)
Import all nonzero entries of a sparse matrix into the index set.
template<class MatrixType >
void exportIdx (MatrixType &matrix) const
Initializes a BCRSMatrix with the indices contained in this MatrixIndexSet.
Detailed Description
Stores the nonzero entries in a sparse matrix.
Member Typedef Documentation
typedef std::size_t Dune::MatrixIndexSet::size_type
Constructor & Destructor Documentation
Dune::MatrixIndexSet::MatrixIndexSet () inline
Default constructor.
Dune::MatrixIndexSet::MatrixIndexSet (size_type rows, size_type cols) inline
Constructor setting the matrix size.
Member Function Documentation
void Dune::MatrixIndexSet::add (size_type i, size_type j) inline
Add an index to the index set.
Referenced by import().
template<class MatrixType > void Dune::MatrixIndexSet::exportIdx (MatrixType & matrix) const inline
Initializes a BCRSMatrix with the indices contained in this MatrixIndexSet.
Template Parameters:
MatrixType Needs to be BCRSMatrix<...>
Parameters:
matrix reference to the MatrixType object
template<class MatrixType > void Dune::MatrixIndexSet::import (const MatrixType & m, size_type rowOffset = 0, size_type colOffset = 0) inline
Import all nonzero entries of a sparse matrix into the index set.
Template Parameters:
MatrixType Needs to be BCRSMatrix<...>
Parameters:
m reference to the MatrixType object
rowOffset don't write to rows<rowOffset
colOffset don't write to cols<colOffset
References add(), and row.
void Dune::MatrixIndexSet::resize (size_type rows, size_type cols) inline
Reset the size of an index set.
References rows().
size_type Dune::MatrixIndexSet::rows () const inline
Return the number of rows.
Referenced by resize().
size_type Dune::MatrixIndexSet::rowsize (size_type row) const inline
Return the number of entries in a given row.
References row.
size_type Dune::MatrixIndexSet::size () const inline
Return the number of entries.
The documentation for this class was generated from the following file:
matrixindexset.hh