dune-istl: Dune::NonoverlappingSchwarzOperator< M, X, Y, C > Class Template Reference
Dune::NonoverlappingSchwarzOperator< M, X, Y, C > Class Template Reference
Operator concept
A nonoverlapping operator with communication object.
#include <dune/istl/novlpschwarz.hh>
Public Types
enum { category = SolverCategory::nonoverlapping }
typedef M matrix_type
The type of the matrix we operate on.
typedef X domain_type
The type of the domain.
typedef Y range_type
The type of the range.
typedef X::field_type field_type
The field type of the range.
typedef C communication_type
The type of the communication object.
typedef C::PIS PIS
typedef C::RI RI
typedef RI::RemoteIndexList RIL
typedef RI::const_iterator RIIterator
typedef RIL::const_iterator RILIterator
typedef M::ConstColIterator ColIterator
typedef M::ConstRowIterator RowIterator
typedef std::multimap< int, int > MM
typedef std::multimap< int,
std::pair< int, RILIterator > > RIMap
typedef RIMap::iterator RIMapit
Public Member Functions
NonoverlappingSchwarzOperator (const matrix_type &A, const communication_type &com)
constructor: just store a reference to a matrix.
virtual void apply (const X &x, Y &y) const
apply operator to x:
virtual void applyscaleadd (field_type alpha, const X &x, Y &y) const
apply operator to x, scale and add:
virtual const matrix_type & getmat () const
get matrix via *
void novlp_op_apply (const X &x, Y &y, field_type alpha) const
Detailed Description
template<class M, class X, class Y, class C>
class Dune::NonoverlappingSchwarzOperator< M, X, Y, C >
A nonoverlapping operator with communication object.
Member Typedef Documentation
template<class M, class X, class Y, class C> typedef M::ConstColIterator Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::ColIterator
template<class M, class X, class Y, class C> typedef C Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::communication_type
The type of the communication object.
template<class M, class X, class Y, class C> typedef X Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::domain_type
The type of the domain.
Reimplemented from Dune::AssembledLinearOperator< M, X, Y >.
template<class M, class X, class Y, class C> typedef X::field_type Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::field_type
The field type of the range.
Reimplemented from Dune::AssembledLinearOperator< M, X, Y >.
template<class M, class X, class Y, class C> typedef M Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::matrix_type
The type of the matrix we operate on.
Reimplemented from Dune::AssembledLinearOperator< M, X, Y >.
template<class M, class X, class Y, class C> typedef std::multimap<int,int> Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::MM
template<class M, class X, class Y, class C> typedef C::PIS Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::PIS
template<class M, class X, class Y, class C> typedef Y Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::range_type
The type of the range.
Reimplemented from Dune::AssembledLinearOperator< M, X, Y >.
template<class M, class X, class Y, class C> typedef C::RI Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::RI
template<class M, class X, class Y, class C> typedef RI::const_iterator Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::RIIterator
template<class M, class X, class Y, class C> typedef RI::RemoteIndexList Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::RIL
template<class M, class X, class Y, class C> typedef RIL::const_iterator Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::RILIterator
template<class M, class X, class Y, class C> typedef std::multimap<int,std::pair<int,RILIterator> > Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::RIMap
template<class M, class X, class Y, class C> typedef RIMap::iterator Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::RIMapit
template<class M, class X, class Y, class C> typedef M::ConstRowIterator Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::RowIterator
Member Enumeration Documentation
template<class M, class X, class Y, class C> anonymous enum
Enumerator:
category
The solver category.
Constructor & Destructor Documentation
template<class M, class X, class Y, class C> Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::NonoverlappingSchwarzOperator (const matrix_type & A, const communication_type & com) inline
constructor: just store a reference to a matrix.
Parameters:
A The assembled matrix.
com The communication object for syncing owner and copy data points. (E.~g. OwnerOverlapCommunication)
Member Function Documentation
template<class M, class X, class Y, class C> virtual void Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::apply (const X & x, Y & y) const inline virtual
apply operator to x:
Implements Dune::LinearOperator< X, Y >.
References Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::novlp_op_apply().
template<class M, class X, class Y, class C> virtual void Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::applyscaleadd (field_type alpha, const X & x, Y & y) const inline virtual
apply operator to x, scale and add:
Implements Dune::LinearOperator< X, Y >.
References Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::novlp_op_apply().
template<class M, class X, class Y, class C> virtual const matrix_type& Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::getmat () const inline virtual
get matrix via *
Implements Dune::AssembledLinearOperator< M, X, Y >.
template<class M, class X, class Y, class C> void Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::novlp_op_apply (const X & x, Y & y, field_type alpha) const inline
References Dune::OwnerOverlapCopyAttributeSet::copy, Dune::OwnerOverlapCopyAttributeSet::overlap, and Dune::OwnerOverlapCopyAttributeSet::owner.
Referenced by Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::apply(), and Dune::NonoverlappingSchwarzOperator< M, X, Y, C >::applyscaleadd().
The documentation for this class was generated from the following file:
novlpschwarz.hh