dune-istl: Dune::LoopSolver< X > Class Template Reference
Dune::LoopSolver< X > Class Template Reference
Iterative Solvers
Preconditioned loop solver.
#include <dune/istl/solvers.hh>
Public Types
typedef X domain_type
The domain type of the operator that we do the inverse for.
typedef X range_type
The range type of the operator that we do the inverse for.
typedef X::field_type field_type
The field type of the operator that we do the inverse for.
Public Member Functions
template<class L , class P >
LoopSolver (L &op, P &prec, double reduction, int maxit, int verbose)
Set up Loop solver.
template<class L , class S , class P >
LoopSolver (L &op, S &sp, P &prec, double reduction, int maxit, int verbose)
Set up loop solver.
virtual void apply (X &x, X &b, InverseOperatorResult &res)
Apply inverse operator,.
virtual void apply (X &x, X &b, double reduction, InverseOperatorResult &res)
apply inverse operator, with given convergence criteria.
Protected Types
enum
Protected Member Functions
void printHeader (std::ostream &s) const
helper function for printing header of solver output
void printOutput (std::ostream &s, const double iter, const DataType &norm, const DataType &norm_old) const
helper function for printing solver output
void printOutput (std::ostream &s, const double iter, const DataType &norm) const
helper function for printing solver output
Detailed Description
template<class X>
class Dune::LoopSolver< X >
Preconditioned loop solver.
Implements a preconditioned loop. Using this class every Preconditioner can be turned into a solver. The solver will apply one preconditioner step in each iteration loop.
Member Typedef Documentation
template<class X> typedef X Dune::LoopSolver< X >::domain_type
The domain type of the operator that we do the inverse for.
Reimplemented from Dune::InverseOperator< X, X >.
template<class X> typedef X::field_type Dune::LoopSolver< X >::field_type
The field type of the operator that we do the inverse for.
Reimplemented from Dune::InverseOperator< X, X >.
template<class X> typedef X Dune::LoopSolver< X >::range_type
The range type of the operator that we do the inverse for.
Reimplemented from Dune::InverseOperator< X, X >.
Member Enumeration Documentation
anonymous enum protected inherited
Constructor & Destructor Documentation
template<class X> template<class L , class P > Dune::LoopSolver< X >::LoopSolver (L & op, P & prec, double reduction, int maxit, int verbose) inline
Set up Loop solver.
Parameters:
op The operator we solve.
prec The preconditioner to apply in each iteration of the loop. Has to inherit from Preconditioner.
reduction The relative defect reduction to achieve when applying the operator.
maxit The maximum number of iteration steps allowed when applying the operator.
verbose The verbosity level.
Verbose levels are:
0 : print nothing
1 : print initial and final defect and statistics
2 : print line for each iteration
References Dune::SolverCategory::sequential.
template<class X> template<class L , class S , class P > Dune::LoopSolver< X >::LoopSolver (L & op, S & sp, P & prec, double reduction, int maxit, int verbose) inline
Set up loop solver.
Parameters:
op The operator we solve.
sp The scalar product to use, e. g. SeqScalarproduct.
prec The preconditioner to apply in each iteration of the loop. Has to inherit from Preconditioner.
reduction The relative defect reduction to achieve when applying the operator.
maxit The maximum number of iteration steps allowed when applying the operator.
verbose The verbosity level.
Verbose levels are:
0 : print nothing
1 : print initial and final defect and statistics
2 : print line for each iteration
Member Function Documentation
template<class X> virtual void Dune::LoopSolver< X >::apply (X & x, X & b, InverseOperatorResult & res) inline virtual
Apply inverse operator,.
Warning:
Note: right hand side b may be overwritten!
Parameters:
x The left hand side to store the result in.
b The right hand side
res Object to store the statistics about applying the operator.
Implements Dune::InverseOperator< X, X >.
References Dune::Preconditioner< X, Y >::apply(), Dune::LinearOperator< X, Y >::applyscaleadd(), Dune::InverseOperatorResult::clear(), Dune::InverseOperatorResult::conv_rate, Dune::InverseOperatorResult::converged, Dune::InverseOperatorResult::elapsed, Dune::InverseOperatorResult::iterations, Dune::Preconditioner< X, Y >::post(), Dune::Preconditioner< X, Y >::pre(), Dune::InverseOperator< X, X >::printHeader(), Dune::InverseOperator< X, X >::printOutput(), and Dune::InverseOperatorResult::reduction.
Referenced by test_Interface().
template<class X> virtual void Dune::LoopSolver< X >::apply (X & x, X & b, double reduction, InverseOperatorResult & res) inline virtual
apply inverse operator, with given convergence criteria.
Warning:
Right hand side b may be overwritten!
Parameters:
x The left hand side to store the result in.
b The right hand side
reduction The minimum defect reduction to achieve.
res Object to store the statistics about applying the operator.
Implements Dune::InverseOperator< X, X >.
void Dune::InverseOperator< X, X >::printHeader (std::ostream & s) const inline protected inherited
helper function for printing header of solver output
References Dune::InverseOperator< X, Y >::iterationSpacing, and Dune::InverseOperator< X, Y >::normSpacing.
Referenced by Dune::LoopSolver< X >::apply(), Dune::GradientSolver< X >::apply(), Dune::CGSolver< X >::apply(), Dune::BiCGSTABSolver< X >::apply(), and Dune::MINRESSolver< X >::apply().
void Dune::InverseOperator< X, X >::printOutput (std::ostream & s, const double iter, const DataType & norm, const DataType & norm_old) const inline protected inherited
helper function for printing solver output
References Dune::InverseOperator< X, Y >::iterationSpacing, and Dune::InverseOperator< X, Y >::normSpacing.
Referenced by Dune::LoopSolver< X >::apply(), Dune::GradientSolver< X >::apply(), Dune::CGSolver< X >::apply(), Dune::BiCGSTABSolver< X >::apply(), and Dune::MINRESSolver< X >::apply().
void Dune::InverseOperator< X, X >::printOutput (std::ostream & s, const double iter, const DataType & norm) const inline protected inherited
helper function for printing solver output
References Dune::InverseOperator< X, Y >::iterationSpacing, and Dune::InverseOperator< X, Y >::normSpacing.
The documentation for this class was generated from the following file:
solvers.hh