dune-istl: Dune::Amg::Transfer< V1, V2, T > Class Template Reference
Dune::Amg::Transfer< V1, V2, T > Class Template Reference
Parallel Algebraic Multigrid
#include <dune/istl/paamg/transfer.hh>
Public Types
typedef V1 Vertex
typedef V2 Vector
Static Public Member Functions
template<typename T1 , typename R >
static void prolongate (const AggregatesMap< Vertex > &aggregates, Vector &coarse, Vector &fine, Vector &fineRedist, T1 damp, R &redistributor=R())
template<typename T1 , typename R >
static void prolongate (const AggregatesMap< Vertex > &aggregates, Vector &coarse, Vector &fine, T1 damp)
static void restrict (const AggregatesMap< Vertex > &aggregates, Vector &coarse, const Vector &fine, T &comm)
Member Typedef Documentation
template<class V1, class V2, class T> typedef V2 Dune::Amg::Transfer< V1, V2, T >::Vector
template<class V1, class V2, class T> typedef V1 Dune::Amg::Transfer< V1, V2, T >::Vertex
Member Function Documentation
template<class V1, class V2, class T> template<typename T1 , typename R > static void Dune::Amg::Transfer< V1, V2, T >::prolongate (const AggregatesMap< Vertex > & aggregates, Vector & coarse, Vector & fine, Vector & fineRedist, T1 damp, R & redistributor = R()) static
Referenced by Dune::Amg::Transfer< V, V1, OwnerOverlapCopyCommunication< T1, T2 > >::prolongate(), and Dune::Amg::Transfer< V, V1, SequentialInformation >::prolongate().
template<class V1, class V2, class T> template<typename T1 , typename R > static void Dune::Amg::Transfer< V1, V2, T >::prolongate (const AggregatesMap< Vertex > & aggregates, Vector & coarse, Vector & fine, T1 damp) static
template<class V1, class V2, class T> static void Dune::Amg::Transfer< V1, V2, T >::restrict (const AggregatesMap< Vertex > & aggregates, Vector & coarse, const Vector & fine, T & comm) static
Referenced by Dune::Amg::Transfer< V, V1, OwnerOverlapCopyCommunication< T1, T2 > >::restrict().
The documentation for this class was generated from the following file:
transfer.hh