dune-istl: Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > > Class Template Reference
Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > > Class Template Reference
#include <dune/istl/supermatrix.hh>
Public Types
typedef Dune::BCRSMatrix
< FieldMatrix< T, n, m >, A > Matrix
typedef Dune::SuperLUMatrix
< Matrix > SuperLUMatrix
typedef
Matrix::row_type::const_iterator CIter
typedef Matrix::size_type size_type
Public Member Functions
SuperMatrixInitializer (SuperLUMatrix &lum)
SuperMatrixInitializer ()
~SuperMatrixInitializer ()
template<typename Iter >
void addRowNnz (const Iter &row) const
template<typename Iter , typename Set >
void addRowNnz (const Iter &row, const Set &s) const
void allocate ()
template<typename Iter >
void countEntries (const Iter &row, const CIter &col) const
void countEntries (size_type colidx) const
void calcColstart () const
template<typename Iter >
void copyValue (const Iter &row, const CIter &col) const
void copyValue (const CIter &col, size_type rowindex, size_type colidx) const
void createMatrix () const
template<typename Iter , typename Map >
void addRowNnz (const Iter &row, const Map &indices) const
Friends
class OverlappingSchwarzInitializer
Member Typedef Documentation
template<class T , class A , int n, int m> typedef Matrix::row_type::const_iterator Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::CIter
template<class T , class A , int n, int m> typedef Dune::BCRSMatrix<FieldMatrix<T,n,m>,A> Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::Matrix
template<class T , class A , int n, int m> typedef Matrix::size_type Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::size_type
template<class T , class A , int n, int m> typedef Dune::SuperLUMatrix<Matrix> Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::SuperLUMatrix
Constructor & Destructor Documentation
template<class T , class A , int n, int m> Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::SuperMatrixInitializer (SuperLUMatrix & lum)
References mat.
template<class T , class A , int n, int m> Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::SuperMatrixInitializer ()
template<class T , class A , int n, int m> Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::~SuperMatrixInitializer ()
Member Function Documentation
template<class T , class A , int n, int m> template<typename Iter > void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::addRowNnz (const Iter & row) const
References mat.
template<class T , class A , int n, int m> template<typename Iter , typename Set > void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::addRowNnz (const Iter & row, const Set & s) const
template<class T , class A , int n, int m> template<typename Iter , typename Map > void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::addRowNnz (const Iter & row, const Map & indices) const
References Dune::Matrix< T, A >::begin(), and mat.
template<class T , class A , int n, int m> void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::allocate ()
template<class T , class A , int n, int m> void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::calcColstart () const
References mat.
template<class T , class A , int n, int m> template<typename Iter > void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::copyValue (const Iter & row, const CIter & col) const
References Dune::BCRSMatrix< B, A >::RealRowIterator< T >::index().
template<class T , class A , int n, int m> void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::copyValue (const CIter & col, size_type rowindex, size_type colidx) const
References mat.
template<class T , class A , int n, int m> template<typename Iter > void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::countEntries (const Iter & row, const CIter & col) const
References Dune::countEntries(), and Dune::BCRSMatrix< B, A >::RealRowIterator< T >::index().
template<class T , class A , int n, int m> void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::countEntries (size_type colidx) const
template<class T , class A , int n, int m> void Dune::SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >::createMatrix () const
References mat.
Friends And Related Function Documentation
template<class T , class A , int n, int m> friend class OverlappingSchwarzInitializer friend
The documentation for this class was generated from the following file:
supermatrix.hh