dune-istl: Dune::Preconditioner< X, Y > Class Template Reference
Dune::Preconditioner< X, Y > Class Template Reference
Preconditioners
Base class for matrix free definition of preconditioners.
#include <dune/istl/preconditioners.hh>
Public Types
typedef X domain_type
The domain type of the preconditioner.
typedef Y range_type
The range type of the preconditioner.
typedef X::field_type field_type
The field type of the preconditioner.
Public Member Functions
virtual void pre (X &x, Y &b)=0
Prepare the preconditioner.
virtual void apply (X &v, const Y &d)=0
Apply one step of the preconditioner to the system A(v)=d.
virtual void post (X &x)=0
Clean up.
virtual ~Preconditioner ()
Detailed Description
template<class X, class Y>
class Dune::Preconditioner< X, Y >
Base class for matrix free definition of preconditioners.
  Note that the operator, which is the basis for the preconditioning,
is supplied to the preconditioner from the outside in the constructor or some other method.
This interface allows the encapsulation of all parallelization
aspects into the preconditioners.
Template Parameters:
X Type of the update
Y Type of the defect
Member Typedef Documentation
template<class X, class Y> typedef X Dune::Preconditioner< X, Y >::domain_type
The domain type of the preconditioner.
Reimplemented in Dune::SeqOverlappingSchwarz< M, X, TM, TD, TA >, Dune::SeqOverlappingSchwarz< M, X, TM, TS, TA >, Dune::Richardson< X, Y >, Dune::SeqILUn< M, X, Y, l >, Dune::SeqILU0< M, X, Y, l >, Dune::SeqJac< M, X, Y, l >, Dune::NonoverlappingBlockPreconditioner< C, P >, Dune::SeqGS< M, X, Y, l >, Dune::BlockPreconditioner< X, Y, C, T >, Dune::SeqSOR< M, X, Y, l >, Dune::ParSSOR< M, X, Y, C >, Dune::SeqSSOR< M, X, Y, l >, and Dune::SeqPardiso< M, X, Y >.
template<class X, class Y> typedef X::field_type Dune::Preconditioner< X, Y >::field_type
The field type of the preconditioner.
Reimplemented in Dune::SeqOverlappingSchwarz< M, X, TM, TD, TA >, Dune::SeqOverlappingSchwarz< M, X, TM, TS, TA >, Dune::Richardson< X, Y >, Dune::SeqILUn< M, X, Y, l >, Dune::SeqILU0< M, X, Y, l >, Dune::SeqJac< M, X, Y, l >, Dune::SeqGS< M, X, Y, l >, Dune::BlockPreconditioner< X, Y, C, T >, Dune::SeqSOR< M, X, Y, l >, Dune::ParSSOR< M, X, Y, C >, Dune::SeqSSOR< M, X, Y, l >, and Dune::SeqPardiso< M, X, Y >.
template<class X, class Y> typedef Y Dune::Preconditioner< X, Y >::range_type
The range type of the preconditioner.
Reimplemented in Dune::SeqOverlappingSchwarz< M, X, TM, TD, TA >, Dune::SeqOverlappingSchwarz< M, X, TM, TS, TA >, Dune::Richardson< X, Y >, Dune::SeqILUn< M, X, Y, l >, Dune::SeqILU0< M, X, Y, l >, Dune::SeqJac< M, X, Y, l >, Dune::NonoverlappingBlockPreconditioner< C, P >, Dune::SeqGS< M, X, Y, l >, Dune::BlockPreconditioner< X, Y, C, T >, Dune::SeqSOR< M, X, Y, l >, Dune::ParSSOR< M, X, Y, C >, Dune::SeqSSOR< M, X, Y, l >, and Dune::SeqPardiso< M, X, Y >.
Constructor & Destructor Documentation
template<class X, class Y> virtual Dune::Preconditioner< X, Y >::~Preconditioner () inline virtual
Member Function Documentation
template<class X, class Y> virtual void Dune::Preconditioner< X, Y >::apply (X & v, const Y & d) pure virtual
Apply one step of the preconditioner to the system A(v)=d.
On entry v=0 and d=b-A(x) (although this might not be computed in that way. On exit v contains the update, i.e one step computes where is the approximate inverse of the operator characterizing the preconditioner.
Parameters:
[out] v The update to be computed
d The current defect.
Implemented in Dune::SeqOverlappingSchwarz< M, X, TM, TD, TA >, Dune::SeqOverlappingSchwarz< M, X, TM, TS, TA >, Dune::SeqOverlappingSchwarz< M, X, TM, TD, TA >, Dune::SeqOverlappingSchwarz< M, X, TM, TS, TA >, Dune::Richardson< X, Y >, Dune::SeqILUn< M, X, Y, l >, Dune::SeqILU0< M, X, Y, l >, Dune::SeqJac< M, X, Y, l >, Dune::NonoverlappingBlockPreconditioner< C, P >, Dune::SeqGS< M, X, Y, l >, Dune::BlockPreconditioner< X, Y, C, T >, Dune::BlockPreconditioner< X, Y, C, T >, Dune::SeqSOR< M, X, Y, l >, Dune::SeqSOR< M, X, Y, l >, Dune::ParSSOR< M, X, Y, C >, Dune::Amg::KAMG< M, X, S, PI, K, A >, Dune::SeqSSOR< M, X, Y, l >, Dune::Amg::AMG< M, X, S, PI, A >, and Dune::SeqPardiso< M, X, Y >.
Referenced by Dune::LoopSolver< X >::apply(), Dune::GradientSolver< X >::apply(), Dune::CGSolver< X >::apply(), Dune::BiCGSTABSolver< X >::apply(), Dune::MINRESSolver< X >::apply(), and Dune::RestartedGMResSolver< X, Y, F >::apply().
template<class X, class Y> virtual void Dune::Preconditioner< X, Y >::post (X & x) pure virtual
Clean up.
This method is called after the last apply call for the linear system to be solved. Memory may be deallocated safely here. x is the solution of the linear equation.
Parameters:
x The right hand side of the equation.
Implemented in Dune::SeqOverlappingSchwarz< M, X, TM, TD, TA >, Dune::SeqOverlappingSchwarz< M, X, TM, TS, TA >, Dune::Richardson< X, Y >, Dune::SeqILUn< M, X, Y, l >, Dune::SeqILU0< M, X, Y, l >, Dune::SeqJac< M, X, Y, l >, Dune::NonoverlappingBlockPreconditioner< C, P >, Dune::SeqGS< M, X, Y, l >, Dune::BlockPreconditioner< X, Y, C, T >, Dune::SeqSOR< M, X, Y, l >, Dune::ParSSOR< M, X, Y, C >, Dune::SeqSSOR< M, X, Y, l >, Dune::Amg::KAMG< M, X, S, PI, K, A >, Dune::Amg::AMG< M, X, S, PI, A >, Dune::SeqPardiso< M, X, Y >, and Dune::Amg::KAmgTwoGrid< Amg >.
Referenced by Dune::LoopSolver< X >::apply(), Dune::GradientSolver< X >::apply(), Dune::CGSolver< X >::apply(), Dune::BiCGSTABSolver< X >::apply(), Dune::MINRESSolver< X >::apply(), and Dune::RestartedGMResSolver< X, Y, F >::apply().
template<class X, class Y> virtual void Dune::Preconditioner< X, Y >::pre (X & x, Y & b) pure virtual
Prepare the preconditioner.
A solver solves a linear operator equation A(x)=b by applying one or several steps of the preconditioner. The method pre() is called before the first apply operation. b and x are right hand side and solution vector of the linear system respectively. It may. e.g., scale the system, allocate memory or compute a (I)LU decomposition. Note: The ILU decomposition could also be computed in the constructor or with a separate method of the derived method if several linear systems with the same matrix are to be solved.
Parameters:
x The left hand side of the equation.
b The right hand side of the equation.
Implemented in Dune::SeqOverlappingSchwarz< M, X, TM, TD, TA >, Dune::SeqOverlappingSchwarz< M, X, TM, TS, TA >, Dune::Richardson< X, Y >, Dune::SeqILUn< M, X, Y, l >, Dune::SeqILU0< M, X, Y, l >, Dune::SeqJac< M, X, Y, l >, Dune::NonoverlappingBlockPreconditioner< C, P >, Dune::SeqGS< M, X, Y, l >, Dune::BlockPreconditioner< X, Y, C, T >, Dune::SeqSOR< M, X, Y, l >, Dune::ParSSOR< M, X, Y, C >, Dune::Amg::KAMG< M, X, S, PI, K, A >, Dune::SeqSSOR< M, X, Y, l >, Dune::Amg::AMG< M, X, S, PI, A >, Dune::SeqPardiso< M, X, Y >, and Dune::Amg::KAmgTwoGrid< Amg >.
Referenced by Dune::LoopSolver< X >::apply(), Dune::GradientSolver< X >::apply(), Dune::CGSolver< X >::apply(), Dune::BiCGSTABSolver< X >::apply(), Dune::MINRESSolver< X >::apply(), and Dune::RestartedGMResSolver< X, Y, F >::apply().
The documentation for this class was generated from the following file:
preconditioners.hh