dune-istl: Dune::RedistributeInterface Struct Reference
Dune::RedistributeInterface Struct Reference
#include <dune/istl/repartition.hh>
Public Member Functions
void setCommunicator (MPI_Comm comm)
template<class Flags , class IS >
void buildSendInterface (const std::vector< int > &toPart, const IS &idxset)
void reserveSpaceForReceiveInterface (int proc, int size)
void addReceiveIndex (int proc, std::size_t idx)
template<typename TG >
void buildReceiveInterface (std::vector< std::pair< TG, int > > &indices)
~RedistributeInterface ()
Constructor & Destructor Documentation
Dune::RedistributeInterface::~RedistributeInterface () inline
Member Function Documentation
void Dune::RedistributeInterface::addReceiveIndex (int proc, std::size_t idx) inline
Referenced by Dune::buildCommunication().
template<typename TG > void Dune::RedistributeInterface::buildReceiveInterface (std::vector< std::pair< TG, int > > & indices) inline
template<class Flags , class IS > void Dune::RedistributeInterface::buildSendInterface (const std::vector< int > & toPart, const IS & idxset) inline
Referenced by Dune::buildCommunication().
void Dune::RedistributeInterface::reserveSpaceForReceiveInterface (int proc, int size) inline
void Dune::RedistributeInterface::setCommunicator (MPI_Comm comm) inline
Referenced by Dune::buildCommunication().
The documentation for this struct was generated from the following file:
repartition.hh