dune-istl: Dune::RedistributeInformation< T > Struct Template Reference
Dune::RedistributeInformation< T > Struct Template Reference
#include <dune/istl/matrixredistribute.hh>
Public Member Functions
bool isSetup () const
template<class D >
void redistribute (const D &from, D &to) const
template<class D >
void redistributeBackward (D &from, const D &to) const
void resetSetup ()
void setNoRows (std::size_t size)
void setNoCopyRows (std::size_t size)
void setNoBackwardsCopyRows (std::size_t size)
std::size_t getRowSize (std::size_t index) const
std::size_t getCopyRowSize (std::size_t index) const
std::size_t getBackwardsCopyRowSize (std::size_t index) const
Member Function Documentation
template<typename T> std::size_t Dune::RedistributeInformation< T >::getBackwardsCopyRowSize (std::size_t index) const inline
Referenced by Dune::redistributeMatrixEntries(), and Dune::redistributeSparsityPattern().
template<typename T> std::size_t Dune::RedistributeInformation< T >::getCopyRowSize (std::size_t index) const inline
Referenced by Dune::redistributeMatrixEntries(), and Dune::redistributeSparsityPattern().
template<typename T> std::size_t Dune::RedistributeInformation< T >::getRowSize (std::size_t index) const inline
Referenced by Dune::redistributeMatrixEntries(), and Dune::redistributeSparsityPattern().
template<typename T> bool Dune::RedistributeInformation< T >::isSetup () const inline
template<typename T> template<class D > void Dune::RedistributeInformation< T >::redistribute (const D & from, D & to) const inline
template<typename T> template<class D > void Dune::RedistributeInformation< T >::redistributeBackward (D & from, const D & to) const inline
Referenced by Dune::Amg::Transfer< V, V1, OwnerOverlapCopyCommunication< T1, T2 > >::prolongate(), and Dune::redistributeSparsityPattern().
template<typename T> void Dune::RedistributeInformation< T >::resetSetup () inline
template<typename T> void Dune::RedistributeInformation< T >::setNoBackwardsCopyRows (std::size_t size) inline
Referenced by Dune::redistributeMatrix().
template<typename T> void Dune::RedistributeInformation< T >::setNoCopyRows (std::size_t size) inline
Referenced by Dune::redistributeMatrix().
template<typename T> void Dune::RedistributeInformation< T >::setNoRows (std::size_t size) inline
Referenced by Dune::redistributeMatrix().
The documentation for this struct was generated from the following file:
matrixredistribute.hh