dune-istl: example.cc File Reference
example.cc File Reference
Classes
class Timer
Functions
void test_basearray ()
template<class V >
void f (V &v)
void test_BlockVector ()
void test_VariableBlockVector ()
void test_FieldMatrix ()
void test_BCRSMatrix ()
void test_IO ()
void test_Iter ()
void test_Interface ()
int main (int argc, char **argv)
Function Documentation
template<class V > void f (V & v)
Referenced by test_BlockVector().
int main (int argc, char ** argv)
References test_basearray(), test_BCRSMatrix(), test_BlockVector(), test_FieldMatrix(), test_Interface(), test_IO(), test_Iter(), and test_VariableBlockVector().
void test_basearray ()
References Dune::base_array_unmanaged< B, A >::begin(), Dune::base_array_unmanaged< B, A >::end(), and Dune::base_array_window< B, A >::move().
Referenced by main().
void test_BCRSMatrix ()
Referenced by main().
void test_BlockVector ()
References f(), Timer::start(), and Timer::stop().
Referenced by main().
void test_FieldMatrix ()
References A.
Referenced by main().
void test_Interface ()
References A, Dune::LoopSolver< X >::apply(), col, and row.
Referenced by main().
void test_IO ()
References A, Dune::BCRSMatrix< B, A >::addindex(), Dune::base_array_unmanaged< B, A >::begin(), Dune::BCRSMatrix< B, A >::begin(), Dune::VariableBlockVector< B, A >::begin(), Dune::VariableBlockVector< B, A >::createbegin(), Dune::BCRSMatrix< B, A >::createbegin(), Dune::VariableBlockVector< B, A >::createend(), Dune::BCRSMatrix< B, A >::createend(), Dune::base_array_unmanaged< B, A >::end(), Dune::BCRSMatrix< B, A >::end(), Dune::VariableBlockVector< B, A >::end(), Dune::BCRSMatrix< B, A >::endindices(), Dune::BCRSMatrix< B, A >::endrowsizes(), Dune::printmatrix(), Dune::printvector(), and Dune::BCRSMatrix< B, A >::setrowsize().
Referenced by main().
void test_Iter ()
References A, Dune::BCRSMatrix< B, A >::begin(), Dune::bilu0_decomposition(), Dune::bilu_backsolve(), Dune::BCRSMatrix< B, A >::createbegin(), Dune::BCRSMatrix< B, A >::createend(), Dune::BCRSMatrix< B, A >::end(), Timer::gettime(), Dune::BCRSMatrix< B, A >::mmv(), Timer::start(), Timer::stop(), Dune::block_vector_unmanaged< B, A >::two_norm(), and Dune::BCRSMatrix< B, A >::umv().
Referenced by main().
void test_VariableBlockVector ()
Referenced by main().