dune-istl: Dune Namespace Reference
Dune Namespace Reference
Namespaces
namespace Amg
Classes
class base_array_unmanaged
A simple array container for objects of type B.
class base_array_window
Extend base_array_unmanaged by functions to manipulate.
class base_array
This container extends base_array_unmanaged by memory management with the usual copy semantics providing the full range of copy constructor, destructor and assignment operators.
class compressed_base_array_unmanaged
A simple array container with non-consecutive index set.
class BCRSMatrix
A sparse block matrix with compressed row storage.
class BDMatrix
A block-diagonal matrix.
class BTDMatrix
A block-tridiagonal matrix.
class block_vector_unmanaged
An unmanaged vector of blocks.
class BlockVector
A vector of blocks with memory management.
class BlockVectorWindow
class compressed_block_vector_unmanaged
class CompressedBlockVectorWindow
class DiagonalMatrix
A diagonal matrix of static size.
class DiagonalMatrixWrapper
class DiagonalRowVectorConst
class DiagonalRowVector
struct const_reference< DiagonalRowVector< K, n > >
struct const_reference< DiagonalRowVectorConst< K, n > >
struct mutable_reference< DiagonalRowVector< K, n > >
struct mutable_reference< DiagonalRowVectorConst< K, n > >
class ContainerWrapperIterator
Iterator class for sparse vector-like containers.
struct BL
compile-time parameter for block recursion depth
struct algmeta_btsolve
struct algmeta_btsolve< 0, withdiag, withrelax >
struct algmeta_btsolve< 0, withdiag, norelax >
struct algmeta_btsolve< 0, nodiag, withrelax >
struct algmeta_btsolve< 0, nodiag, norelax >
struct algmeta_bdsolve
struct algmeta_bdsolve< 0, withrelax >
struct algmeta_bdsolve< 0, norelax >
struct algmeta_itsteps
struct algmeta_itsteps< 0 >
class MatrixBlockError
class ILUSubdomainSolver
base class encapsulating common algorithms of ILU0SubdomainSolver and ILUNSubdomainSolver.
class ILU0SubdomainSolver
Exact subdomain solver using ILU(p) with appropriate p.
class ILUNSubdomainSolver
class ISTLError
derive error class from the base class in common
class Matrix
A generic dynamic dense matrix.
class MatrixIndexSet
Stores the nonzero entries in a sparse matrix.
class MatrixMarketFormatError
struct mm_multipliers
struct mm_multipliers< BCRSMatrix< FieldMatrix< B, i, j >, A > >
struct MatMultMatResult
Helper TMP to get the result type of a sparse matrix matrix multiplication ()
struct MatMultMatResult< FieldMatrix< T, n, k >, FieldMatrix< T, k, m > >
struct MatMultMatResult< BCRSMatrix< FieldMatrix< T, n, k >, A >, BCRSMatrix< FieldMatrix< T, k, m >, A1 > >
struct RedistributeInformation
class RedistributeInformation< OwnerOverlapCopyCommunication< T, T1 > >
struct CommMatrixRowSize
Utility class to communicate and set the row sizes of a redistributed matrix.
struct CommMatrixSparsityPattern
Utility class to communicate and build the sparsity pattern of a redistributed matrix.
struct CommPolicy< CommMatrixSparsityPattern< M, I > >
struct CommMatrixRow
Utility class for comunicating the matrix entries.
struct CommPolicy< CommMatrixRow< M, I > >
struct MatrixRowSizeGatherScatter
struct MatrixCopyRowSizeGatherScatter
struct MatrixSparsityPatternGatherScatter
struct MatrixRowGatherScatter
struct CheckIfDiagonalPresent
Check whether the a matrix has diagonal values on blocklevel recursion levels.
struct CheckIfDiagonalPresent< Matrix, 0, l >
struct CheckIfDiagonalPresent< MultiTypeBlockMatrix< T1, T2, T3, T4, T5, T6, T7, T8, T9 >, blocklevel, l >
struct MatrixDimension
struct MatrixDimension< BCRSMatrix< B, TA > >
struct MatrixDimension< BCRSMatrix< FieldMatrix< B, n, m >, TA > >
struct MatrixDimension< FieldMatrix< K, n, m > >
struct MatrixDimension< Matrix< FieldMatrix< K, n, m >, TA > >
struct IsMatrix
Test whether a type is an ISTL Matrix.
struct IsMatrix< DenseMatrix< T > >
struct IsMatrix< BCRSMatrix< T, A > >
class NonoverlappingSchwarzOperator
A nonoverlapping operator with communication object.
class NonoverlappingSchwarzScalarProduct
Nonoverlapping Scalar Product with communication object.
struct ScalarProductChooser< X, C, SolverCategory::nonoverlapping >
class NonoverlappingBlockPreconditioner
Nonoverlapping parallel preconditioner.
class LinearOperator
A linear operator.
class AssembledLinearOperator
A linear operator exporting itself in matrix form.
class MatrixAdapter
Adapter to turn a matrix into a linear operator.
class OverlappingSchwarzInitializer
Initializer for SuperLU Matrices representing the subdomains.
struct AdditiveSchwarzMode
Tag that the tells the schwarz method to be additive.
struct MultiplicativeSchwarzMode
Tag that tells the Schwarz method to be multiplicative.
struct SymmetricMultiplicativeSchwarzMode
Tag that tells the Schwarz method to be multiplicative and symmetric.
class DynamicMatrixSubdomainSolver< BCRSMatrix< FieldMatrix< K, n, n >, Al >, X, Y >
struct OverlappingAssigner
class OverlappingAssigner< DynamicMatrixSubdomainSolver< BCRSMatrix< FieldMatrix< K, n, n >, Al >, X, Y > >
struct OverlappingAssigner< SuperLU< BCRSMatrix< FieldMatrix< T, n, m >, A > > >
class OverlappingAssignerILUBase
class OverlappingAssigner< ILU0SubdomainSolver< M, X, Y > >
class OverlappingAssigner< ILUNSubdomainSolver< M, X, Y > >
struct AdditiveAdder
struct AdditiveAdder< S, BlockVector< FieldVector< T, n >, A > >
struct MultiplicativeAdder
struct MultiplicativeAdder< S, BlockVector< FieldVector< T, n >, A > >
struct AdderSelector
template meta program for choosing how to add the correction.
struct AdderSelector< AdditiveSchwarzMode, X, S >
struct AdderSelector< MultiplicativeSchwarzMode, X, S >
struct AdderSelector< SymmetricMultiplicativeSchwarzMode, X, S >
struct IteratorDirectionSelector
Helper template meta program for application of overlapping schwarz.
struct IteratorDirectionSelector< T1, T2, false >
struct SeqOverlappingSchwarzApplier
Helper template meta program for application of overlapping schwarz.
struct SeqOverlappingSchwarzApplier< SeqOverlappingSchwarz< M, X, SymmetricMultiplicativeSchwarzMode, TD, TA > >
struct SeqOverlappingSchwarzAssembler
struct SeqOverlappingSchwarzAssembler< DynamicMatrixSubdomainSolver< BCRSMatrix< FieldMatrix< K, n, n >, Al >, X, Y > >
struct SeqOverlappingSchwarzAssembler< SuperLU< T > >
struct SeqOverlappingSchwarzAssemblerILUBase
struct SeqOverlappingSchwarzAssembler< ILU0SubdomainSolver< M, X, Y > >
struct SeqOverlappingSchwarzAssembler< ILUNSubdomainSolver< M, X, Y > >
class SeqOverlappingSchwarz
Sequential overlapping Schwarz preconditioner.
struct SeqOverlappingSchwarzDomainSize
struct SeqOverlappingSchwarzDomainSize< BCRSMatrix< FieldMatrix< T, n, m >, A > >
struct OwnerOverlapCopyAttributeSet
Attribute set for overlapping schwarz.
class IndexInfoFromGrid
Information about the index distribution.
class OwnerOverlapCopyCommunication
A class setting up standard communication for a two-valued attribute set with owner/overlap/copy semantics.
struct PropertyMapTypeSelector< Amg::VertexVisitedTag, Amg::PropertiesGraph< G, Amg::VertexProperties, EP, VM, EM > >
struct CommPolicy< Amg::GlobalAggregatesMap< T, TI > >
class SeqPardiso
The sequential Pardiso preconditioner.
struct IsDirectSolver< SeqPardiso< M, X, Y > >
class Preconditioner
Base class for matrix free definition of preconditioners.
class SeqSSOR
Sequential SSOR preconditioner.
class SeqSOR
Sequential SOR preconditioner.
class SeqGS
Sequential Gauss Seidel preconditioner.
class SeqJac
The sequential jacobian preconditioner.
class SeqILU0
Sequential ILU0 preconditioner.
class SeqILUn
Sequential ILU(n) preconditioner.
class Richardson
Richardson preconditioner.
struct RedistributeInterface
class ScalarProduct
Base class for scalar product and norm computation.
struct ScalarProductChooser
Choose the approriate scalar product for a solver category.
class SeqScalarProduct
Default implementation for the scalar case.
struct ScalarProductChooser< X, C, SolverCategory::sequential >
class ScaledIdentityMatrix
A multiple of the identity matrix of static size.
class OverlappingSchwarzOperator
An overlapping schwarz operator.
class OverlappingSchwarzScalarProduct
Scalar product for overlapping schwarz methods.
struct ScalarProductChooser< X, C, SolverCategory::overlapping >
class ParSSOR
A parallel SSOR preconditioner.
class BlockPreconditioner
Block parallel preconditioner.
struct SolverCategory
Categories for the solvers.
struct InverseOperatorResult
Statistics about the application of an inverse operator.
class InverseOperator
Abstract base class for all solvers.
class LoopSolver
Preconditioned loop solver.
class GradientSolver
gradient method
class CGSolver
conjugate gradient method
class BiCGSTABSolver
Bi-conjugate Gradient Stabilized (BiCG-STAB)
class MINRESSolver
Minimal Residual Method (MINRES)
class RestartedGMResSolver
implements the Generalized Minimal Residual (GMRes) method
struct IsDirectSolver
class SuperLU
struct SuperLUSolveChooser
struct SuperLUDenseMatChooser
struct SuperLUQueryChooser
struct QuerySpaceChooser
struct SuperLUDenseMatChooser< double >
struct SuperLUSolveChooser< double >
struct QuerySpaceChooser< double >
class SuperLU< BCRSMatrix< FieldMatrix< T, n, m >, A > >
SuperLu Solver.
struct IsDirectSolver< SuperLU< BCRSMatrix< FieldMatrix< T, n, m >, A > > >
struct SuperMatrixCreateSparseChooser
struct SuperMatrixPrinter
struct SuperMatrixCreateSparseChooser< float >
struct SuperMatrixPrinter< float >
class MatrixRowSet
Provides access to an iterator over all matrix rows.
class MatrixRowSubset
Provides access to an iterator over an arbitrary subset of matrix rows.
struct GetSuperLUType
struct GetSuperLUType< double >
struct GetSuperLUType< float >
struct GetSuperLUType< std::complex< double > >
struct GetSuperLUType< std::complex< float > >
struct SuperLUMatrix
Utility class for converting an ISTL Matrix into a SsuperLU Matrix.
struct SuperMatrixInitializer
class SuperLUMatrix< BCRSMatrix< FieldMatrix< B, n, m >, TA > >
Coverter for BCRSMatrix to SuperLU Matrix.
class SuperMatrixInitializer< BCRSMatrix< FieldMatrix< T, n, m >, A > >
class VariableBlockVector
A Vector of blocks with different blocksizes.
Typedefs
typedef std::size_t idxtype
Enumerations
enum WithDiagType { withdiag = 1, nodiag = 0 }
enum WithRelaxType { withrelax = 1, norelax = 0 }
Functions
template<class K , class A >
std::ostream & operator<< (std::ostream &s, const BlockVector< K, A > &v)
Send BlockVector to an output stream.
template<class K , int n>
void istl_assign_to_fmatrix (FieldMatrix< K, n, n > &fm, const DiagonalMatrix< K, n > &s)
template<class M , class X , class Y >
void bltsolve (const M &A, X &v, const Y &d)
block lower triangular solve
template<class M , class X , class Y , class K >
void bltsolve (const M &A, X &v, const Y &d, const K &w)
relaxed block lower triangular solve
template<class M , class X , class Y >
void ubltsolve (const M &A, X &v, const Y &d)
unit block lower triangular solve
template<class M , class X , class Y , class K >
void ubltsolve (const M &A, X &v, const Y &d, const K &w)
relaxed unit block lower triangular solve
template<class M , class X , class Y >
void butsolve (const M &A, X &v, const Y &d)
block upper triangular solve
template<class M , class X , class Y , class K >
void butsolve (const M &A, X &v, const Y &d, const K &w)
relaxed block upper triangular solve
template<class M , class X , class Y >
void ubutsolve (const M &A, X &v, const Y &d)
unit block upper triangular solve
template<class M , class X , class Y , class K >
void ubutsolve (const M &A, X &v, const Y &d, const K &w)
relaxed unit block upper triangular solve
template<class M , class X , class Y , int l>
void bltsolve (const M &A, X &v, const Y &d, BL< l > bl)
block lower triangular solve
template<class M , class X , class Y , class K , int l>
void bltsolve (const M &A, X &v, const Y &d, const K &w, BL< l > bl)
relaxed block lower triangular solve
template<class M , class X , class Y , int l>
void ubltsolve (const M &A, X &v, const Y &d, BL< l > bl)
unit block lower triangular solve
template<class M , class X , class Y , class K , int l>
void ubltsolve (const M &A, X &v, const Y &d, const K &w, BL< l > bl)
relaxed unit block lower triangular solve
template<class M , class X , class Y , int l>
void butsolve (const M &A, X &v, const Y &d, BL< l > bl)
block upper triangular solve
template<class M , class X , class Y , class K , int l>
void butsolve (const M &A, X &v, const Y &d, const K &w, BL< l > bl)
relaxed block upper triangular solve
template<class M , class X , class Y , int l>
void ubutsolve (const M &A, X &v, const Y &d, BL< l > bl)
unit block upper triangular solve
template<class M , class X , class Y , class K , int l>
void ubutsolve (const M &A, X &v, const Y &d, const K &w, BL< l > bl)
relaxed unit block upper triangular solve
template<class M , class X , class Y >
void bdsolve (const M &A, X &v, const Y &d)
block diagonal solve, no relaxation
template<class M , class X , class Y , class K >
void bdsolve (const M &A, X &v, const Y &d, const K &w)
block diagonal solve, with relaxation
template<class M , class X , class Y , int l>
void bdsolve (const M &A, X &v, const Y &d, BL< l > bl)
block diagonal solve, no relaxation
template<class M , class X , class Y , class K , int l>
void bdsolve (const M &A, X &v, const Y &d, const K &w, BL< l > bl)
block diagonal solve, with relaxation
template<class M , class X , class Y , class K >
void dbgs (const M &A, X &x, const Y &b, const K &w)
GS step.
template<class M , class X , class Y , class K , int l>
void dbgs (const M &A, X &x, const Y &b, const K &w, BL< l > bl)
GS step.
template<class M , class X , class Y , class K >
void bsorf (const M &A, X &x, const Y &b, const K &w)
SOR step.
template<class M , class X , class Y , class K , int l>
void bsorf (const M &A, X &x, const Y &b, const K &w, BL< l > bl)
SOR step.
template<class M , class X , class Y , class K >
void bsorb (const M &A, X &x, const Y &b, const K &w)
SSOR step.
template<class M , class X , class Y , class K , int l>
void bsorb (const M &A, X &x, const Y &b, const K &w, BL< l > bl)
SSOR step.
template<class M , class X , class Y , class K >
void dbjac (const M &A, X &x, const Y &b, const K &w)
Jacobi step.
template<class M , class X , class Y , class K , int l>
void dbjac (const M &A, X &x, const Y &b, const K &w, BL< l > bl)
Jacobi step.
template<class M >
void bilu0_decomposition (M &A)
compute ILU decomposition of A. A is overwritten by its decomposition
template<class M , class X , class Y >
void bilu_backsolve (const M &A, X &v, const Y &d)
LU backsolve with stored inverse.
template<class M >
M::field_type & firstmatrixelement (M &A)
template<class K , int n, int m>
K & firstmatrixelement (FieldMatrix< K, n, m > &A)
template<class K >
K & firstmatrixelement (FieldMatrix< K, 1, 1 > &A)
template<class M >
void bilu_decomposition (const M &A, int n, M &ILU)
template<class V >
void recursive_printvector (std::ostream &s, const V &v, std::string rowtext, int &counter, int columns, int width, int precision)
template<class K , int n>
void recursive_printvector (std::ostream &s, const FieldVector< K, n > &v, std::string rowtext, int &counter, int columns, int width, int precision)
template<class V >
void printvector (std::ostream &s, const V &v, std::string title, std::string rowtext, int columns=1, int width=10, int precision=2)
print an ISTL vector
void fill_row (std::ostream &s, int m, int width, int precision)
print a row of zeros for a non-existing block
template<class M >
void print_row (std::ostream &s, const M &A, typename M::size_type I, typename M::size_type J, typename M::size_type therow, int width, int precision)
print one row of a matrix
template<class K , int n, int m>
void print_row (std::ostream &s, const FieldMatrix< K, n, m > &A, typename FieldMatrix< K, n, m >::size_type I, typename FieldMatrix< K, n, m >::size_type J, typename FieldMatrix< K, n, m >::size_type therow, int width, int precision)
print one row of a matrix, specialization for FieldMatrix
template<class K >
void print_row (std::ostream &s, const FieldMatrix< K, 1, 1 > &A, typename FieldMatrix< K, 1, 1 >::size_type I, typename FieldMatrix< K, 1, 1 >::size_type J, typename FieldMatrix< K, 1, 1 >::size_type therow, int width, int precision)
print one row of a matrix, specialization for FieldMatrix<K,1,1>
template<class M >
void printmatrix (std::ostream &s, const M &A, std::string title, std::string rowtext, int width=10, int precision=2)
Prints a generic block matrix.
template<class B , int n, int m, class A >
void printSparseMatrix (std::ostream &s, const BCRSMatrix< FieldMatrix< B, n, m >, A > &mat, std::string title, std::string rowtext, int width=3, int precision=2)
Prints a BCRSMatrix with fixed sized blocks.
template<class FieldType , int rows, int cols>
void writeMatrixToMatlabHelper (const FieldMatrix< FieldType, rows, cols > &matrix, int rowOffset, int colOffset, std::ostream &s)
Helper method for the writeMatrixToMatlab routine.
template<class MatrixType >
void writeMatrixToMatlabHelper (const MatrixType &matrix, int externalRowOffset, int externalColOffset, std::ostream &s)
Helper method for the writeMatrixToMatlab routine.
template<class MatrixType >
void writeMatrixToMatlab (const MatrixType &matrix, const std::string &filename, int outputPrecision=18)
Writes sparse matrix in a Matlab-readable format.
void mm_read_header (std::size_t &rows, std::size_t &cols, MMHeader &header, std::istream &istr, bool isVector)
template<typename T , typename A , int entries>
void mm_read_vector_entries (Dune::BlockVector< Dune::FieldVector< T, entries >, A > &vector, std::size_t size, std::istream &istr)
template<typename T , typename A , int entries>
void readMatrixMarket (Dune::BlockVector< Dune::FieldVector< T, entries >, A > &vector, std::istream &istr)
Reads a BlockVector from a matrix market file.
template<typename T , typename A , int brows, int bcols>
void readMatrixMarket (Dune::BCRSMatrix< Dune::FieldMatrix< T, brows, bcols >, A > &matrix, std::istream &istr)
Reads a sparse matrix from a matrix market file.
template<typename B , int i, int j>
void mm_print_entry (const FieldMatrix< B, i, j > &entry, typename FieldMatrix< B, i, j >::size_type rowidx, typename FieldMatrix< B, i, j >::size_type colidx, std::ostream &ostr)
template<typename V >
void mm_print_vector_entry (const V &entry, std::ostream &ostr, const integral_constant< int, 1 > &)
template<typename V >
void mm_print_vector_entry (const V &vector, std::ostream &ostr, const integral_constant< int, 0 > &)
template<typename T , typename A , int i>
std::size_t countEntries (const BlockVector< FieldVector< T, i >, A > &vector)
template<typename V >
void writeMatrixMarket (const V &vector, std::ostream &ostr, const integral_constant< int, 0 > &)
template<typename M >
void writeMatrixMarket (const M &matrix, std::ostream &ostr, const integral_constant< int, 1 > &)
template<typename M >
void writeMatrixMarket (const M &matrix, std::ostream &ostr)
writes a ISTL matrix or vector to a stream in matrix market format.
template<typename M >
void storeMatrixMarket (const M &matrix, std::string filename)
Stores a parallel matrix/vector in matrix market format in a file.
template<typename M , typename G , typename L >
void storeMatrixMarket (const M &matrix, std::string filename, const OwnerOverlapCopyCommunication< G, L > &comm, bool storeIndices=true)
Stores a parallel matrix/vector in matrix market format in a file.
template<typename M , typename G , typename L >
void loadMatrixMarket (M &matrix, const std::string &filename, OwnerOverlapCopyCommunication< G, L > &comm, bool readIndices=true)
Load a parallel matrix/vector stored in matrix market format.
template<typename M >
void loadMatrixMarket (M &matrix, const std::string &filename)
Load a matrix/vector stored in matrix market format.
template<class T , class A , class A1 , class A2 , int n, int m, int k>
void matMultTransposeMat (BCRSMatrix< FieldMatrix< T, n, k >, A > &res, const BCRSMatrix< FieldMatrix< T, n, m >, A1 > &mat, const BCRSMatrix< FieldMatrix< T, k, m >, A2 > &matt, bool tryHard=false)
Calculate product of a sparse matrix with a transposed sparse matrices ().
template<class T , class A , class A1 , class A2 , int n, int m, int k>
void matMultMat (BCRSMatrix< FieldMatrix< T, n, m >, A > &res, const BCRSMatrix< FieldMatrix< T, n, k >, A1 > &mat, const BCRSMatrix< FieldMatrix< T, k, m >, A2 > &matt, bool tryHard=false)
Calculate product of two sparse matrices ().
template<class T , class A , class A1 , class A2 , int n, int m, int k>
void transposeMatMultMat (BCRSMatrix< FieldMatrix< T, n, m >, A > &res, const BCRSMatrix< FieldMatrix< T, k, n >, A1 > &mat, const BCRSMatrix< FieldMatrix< T, k, m >, A2 > &matt, bool tryHard=false)
Calculate product of a transposed sparse matrix with another sparse matrices ().
template<typename M , typename C >
void redistributeSparsityPattern (M &origMatrix, M &newMatrix, C &origComm, C &newComm, RedistributeInformation< C > &ri)
template<typename M , typename C >
void redistributeMatrixEntries (M &origMatrix, M &newMatrix, C &origComm, C &newComm, RedistributeInformation< C > &ri)
template<typename M , typename C >
void redistributeMatrix (M &origMatrix, M &newMatrix, C &origComm, C &newComm, RedistributeInformation< C > &ri)
Redistribute a matrix according to given domain decompositions.
template<class M >
int countNonZeros (const M &matrix)
Get the number of nonzero fields in the matrix.
template<class M , class C >
void printGlobalSparseMatrix (const M &mat, C &ooc, std::ostream &os)
template<typename G , typename EP , typename VM , typename EM >
PropertyMapTypeSelector
< Amg::VertexVisitedTag,
Amg::PropertiesGraph< G,
Amg::VertexProperties, EP, VM,
EM > >::Type get (const Amg::VertexVisitedTag &tag, Amg::PropertiesGraph< G, Amg::VertexProperties, EP, VM, EM > &graph)
template<class G , class T1 , class T2 >
void fillIndexSetHoles (const G &graph, Dune::OwnerOverlapCopyCommunication< T1, T2 > &oocomm)
Fills the holes in an index set.
template<class G , class T1 , class T2 >
bool buildCommunication (const G &graph, std::vector< int > &realparts, Dune::OwnerOverlapCopyCommunication< T1, T2 > &oocomm, Dune::OwnerOverlapCopyCommunication< T1, T2 > *&outcomm, RedistributeInterface &redistInf, bool verbose=false)
template<class S , class T >
void print_carray (S &os, T *array, std::size_t l)
bool isValidGraph (std::size_t noVtx, std::size_t gnoVtx, idxtype noEdges, idxtype *xadj, idxtype *adjncy, bool checkSymmetry)
template<class M , class T1 , class T2 >
bool commGraphRepartition (const M &mat, Dune::OwnerOverlapCopyCommunication< T1, T2 > &oocomm, int nparts, Dune::OwnerOverlapCopyCommunication< T1, T2 > *&outcomm, RedistributeInterface &redistInf, bool verbose=false)
template<class G , class T1 , class T2 >
bool graphRepartition (const G &graph, Dune::OwnerOverlapCopyCommunication< T1, T2 > &oocomm, int nparts, Dune::OwnerOverlapCopyCommunication< T1, T2 > *&outcomm, RedistributeInterface &redistInf, bool verbose=false)
execute a graph repartition for a giving graph and indexset.
template<class M , class K , int n>
void istl_assign_to_fmatrix (DenseMatrix< M > &fm, const ScaledIdentityMatrix< K, n > &s)
template<class T , class A , int n, int m>
void writeCompColMatrixToMatlab (const SuperLUMatrix< BCRSMatrix< FieldMatrix< T, n, m >, A > > &mat, std::ostream &os)
template<class F , class MRS >
void copyToSuperMatrix (F &initializer, const MRS &mrs)
template<class F , class M , class S >
void copyToSuperMatrix (F &initializer, const MatrixRowSubset< M, S > &mrs)
template<class B , class TA , int n, int m>
bool operator== (SuperLUMatrix< BCRSMatrix< FieldMatrix< B, n, m >, TA > > &sla, BCRSMatrix< FieldMatrix< B, n, m >, TA > &a)
Typedef Documentation
typedef std::size_t Dune::idxtype
Function Documentation
template<class G , class T1 , class T2 > bool Dune::buildCommunication (const G & graph, std::vector< int > & realparts, Dune::OwnerOverlapCopyCommunication< T1, T2 > & oocomm, Dune::OwnerOverlapCopyCommunication< T1, T2 > *& outcomm, RedistributeInterface & redistInf, bool verbose = false)
References Dune::RedistributeInterface::addReceiveIndex(), Dune::RedistributeInterface::buildSendInterface(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::communicator(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::getSolverCategory(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::globalLookup(), index, Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::indexSet(), and Dune::RedistributeInterface::setCommunicator().
Referenced by commGraphRepartition(), and graphRepartition().
template<class M , class T1 , class T2 > bool Dune::commGraphRepartition (const M & mat, Dune::OwnerOverlapCopyCommunication< T1, T2 > & oocomm, int nparts, Dune::OwnerOverlapCopyCommunication< T1, T2 > *& outcomm, RedistributeInterface & redistInf, bool verbose = false)
References buildCommunication(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::buildGlobalLookup(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::communicator(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::copyOwnerToAll(), fillIndexSetHoles(), isValidGraph(), print_carray(), and Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::remoteIndices().
Referenced by Dune::Amg::repartitionAndDistributeMatrix().
template<class F , class MRS > void Dune::copyToSuperMatrix (F & initializer, const MRS & mrs)
References col, and row.
Referenced by Dune::SeqOverlappingSchwarzAssembler< SuperLU< T > >::assembleLocalProblems().
template<class F , class M , class S > void Dune::copyToSuperMatrix (F & initializer, const MatrixRowSubset< M, S > & mrs)
References Dune::MatrixRowSubset< M, S >::begin(), col, Dune::MatrixRowSubset< M, S >::end(), index, Dune::MatrixRowSubset< M, S >::matrix(), Dune::Matrix< T, A >::N(), row, and Dune::MatrixRowSubset< M, S >::rowIndexSet().
template<class G , class T1 , class T2 > void Dune::fillIndexSetHoles (const G & graph, Dune::OwnerOverlapCopyCommunication< T1, T2 > & oocomm)
Fills the holes in an index set.
In general the index set only needs to know those indices where communication my occur. In usual FE computations these are just those near the processor boundaries.
For the repartitioning we need to know all all indices for which data is stored. The missing indices will be created in this method.
Parameters:
graph The graph to reparition.
oocomm The communication information.
References Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::buildGlobalLookup(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::communicator(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::freeGlobalLookup(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::globalLookup(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::indexSet(), Dune::OwnerOverlapCopyAttributeSet::owner, and Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::remoteIndices().
Referenced by commGraphRepartition(), and graphRepartition().
template<typename G , typename EP , typename VM , typename EM > PropertyMapTypeSelector<Amg::VertexVisitedTag,Amg::PropertiesGraph<G,Amg::VertexProperties,EP,VM,EM> >::Type Dune::get (const Amg::VertexVisitedTag & tag, Amg::PropertiesGraph< G, Amg::VertexProperties, EP, VM, EM > & graph)
References Dune::Amg::VertexProperties::VISITED.
template<class G , class T1 , class T2 > bool Dune::graphRepartition (const G & graph, Dune::OwnerOverlapCopyCommunication< T1, T2 > & oocomm, int nparts, Dune::OwnerOverlapCopyCommunication< T1, T2 > *& outcomm, RedistributeInterface & redistInf, bool verbose = false)
execute a graph repartition for a giving graph and indexset.
This function provides repartition functionality using the PARMETIS library
Parameters:
graph The given graph to repartition
oocomm The parallel information about the graph.
nparts The number of domains the repartitioning should achieve.
[out] outcomm Pointer store the parallel information of the redistributed domains in.
redistInf Redistribute interface
verbose Verbosity flag to give out additional information.
References buildCommunication(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::buildGlobalLookup(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::communicator(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::copyCopyToAll(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::copyOwnerToAll(), fillIndexSetHoles(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::getSolverCategory(), Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::globalLookup(), index, and Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::indexSet().
Referenced by Dune::Amg::repartitionAndDistributeMatrix().
template<class M , class K , int n> void Dune::istl_assign_to_fmatrix (DenseMatrix< M > & fm, const ScaledIdentityMatrix< K, n > & s)
References Dune::ScaledIdentityMatrix< K, n >::scalar().
bool Dune::isValidGraph (std::size_t noVtx, std::size_t gnoVtx, idxtype noEdges, idxtype * xadj, idxtype * adjncy, bool checkSymmetry) inline
Referenced by commGraphRepartition().
template<class K , class A > std::ostream& Dune::operator<< (std::ostream & s, const BlockVector< K, A > & v)
Send BlockVector to an output stream.
template<class B , class TA , int n, int m> bool Dune::operator== (SuperLUMatrix< BCRSMatrix< FieldMatrix< B, n, m >, TA > > & sla, BCRSMatrix< FieldMatrix< B, n, m >, TA > & a)
template<class S , class T > void Dune::print_carray (S & os, T * array, std::size_t l) inline
Referenced by commGraphRepartition().
template<class M , class C > void Dune::printGlobalSparseMatrix (const M & mat, C & ooc, std::ostream & os)
Referenced by Dune::Amg::repartitionAndDistributeMatrix().
template<typename M , typename C > void Dune::redistributeMatrix (M & origMatrix, M & newMatrix, C & origComm, C & newComm, RedistributeInformation< C > & ri)
Redistribute a matrix according to given domain decompositions.
All the parameters for this function can be obtained by calling graphRepartition with the graph of the original matrix.
Parameters:
origMatrix The matrix on the original partitioning.
newMatrix An empty matrix to store the new redistributed matrix in.
origComm The parallel information of the original partitioning.
newComm The parallel information of the new partitioning.
ri The remote index information between the original and the new partitioning. Upon exit of this method it will be prepared for copying from owner to owner vertices for data redistribution.
Template Parameters:
M The matrix type. It is assumed to be sparse. E.g. BCRSMatrix.
C The type of the parallel information, see OwnerOverlapCopyCommunication.
References redistributeMatrixEntries(), redistributeSparsityPattern(), Dune::RedistributeInformation< T >::setNoBackwardsCopyRows(), Dune::RedistributeInformation< T >::setNoCopyRows(), and Dune::RedistributeInformation< T >::setNoRows().
Referenced by Dune::Amg::repartitionAndDistributeMatrix().
template<typename M , typename C > void Dune::redistributeMatrixEntries (M & origMatrix, M & newMatrix, C & origComm, C & newComm, RedistributeInformation< C > & ri)
References Dune::RedistributeInformation< T >::getBackwardsCopyRowSize(), Dune::RedistributeInformation< T >::getCopyRowSize(), Dune::RedistributeInformation< T >::getRowSize(), Dune::SolverCategory::nonoverlapping, and printmatrix().
Referenced by Dune::Amg::MatrixHierarchy< M, PI, A >::recalculateGalerkin(), and redistributeMatrix().
template<typename M , typename C > void Dune::redistributeSparsityPattern (M & origMatrix, M & newMatrix, C & origComm, C & newComm, RedistributeInformation< C > & ri)
References col, Dune::RedistributeInformation< T >::getBackwardsCopyRowSize(), Dune::RedistributeInformation< T >::getCopyRowSize(), Dune::RedistributeInformation< T >::getRowSize(), Dune::SolverCategory::nonoverlapping, Dune::RedistributeInformation< T >::redistributeBackward(), and row.
Referenced by redistributeMatrix().
template<class T , class A , int n, int m> void Dune::writeCompColMatrixToMatlab (const SuperLUMatrix< BCRSMatrix< FieldMatrix< T, n, m >, A > > & mat, std::ostream & os)
References col, mat, and row.